### ISSUE TITLE
TextImage Brick

### ISSUE THREAD

**Issue by kuschti** [donaier/lustenberger1862#10]
* CKEditor
* Bild
* Checkbox: Bild rechts
* Checkbox: 50% / 50% Verhältniss

![bildschirmfoto 2015-05-09 um 19 35 24](https://cloud.githubusercontent.com/assets/1425929/7551252/a4a0d51c-f682-11e4-94a9-71ec4a172e77.png)
![bildschirmfoto 2015-05-09 um 19 35 31](https://cloud.githubusercontent.com/assets/1425929/7551253/a4a1817e-f682-11e4-89ad-75f0d7251674.png)
![bildschirmfoto 2015-05-09 um 19 35 48](https://cloud.githubusercontent.com/assets/1425929/7551254/a4a28196-f682-11e4-80a0-7e1cfea71d01.png)

**Comment by donaier** [comment]
done
