### ISSUE TITLE
Teaser Full

### ISSUE THREAD

**Issue by kuschti** [donaier/lustenberger1862#6]
* ckeditor
* Bild
* Link + Linktext
* Auswahl: Hintergrund weiss, hellgrau, grau, dunkelgrau
* Checkbox: Bild rechts
* Checkbox: 50% / 50% Verhältniss
* Checkbox: Text zentriert

Variante 1
![bildschirmfoto 2015-05-09 um 19 17 57](https://cloud.githubusercontent.com/assets/1425929/7551204/71259440-f680-11e4-85a6-40e40e575368.png)

Variante 2
![bildschirmfoto 2015-05-09 um 19 18 12](https://cloud.githubusercontent.com/assets/1425929/7551205/78b85314-f680-11e4-842d-21a778677db6.png)

**Comment by donaier** [comment]
done
