### ISSUE TITLE
Teaser 3er

### ISSUE THREAD

**Issue by kuschti** [donaier/lustenberger1862#8]
* Titel (optional)
* Subtitel
* Bild
* Link
* Linktext (optional, wenn ausgefüllt = button)

![bildschirmfoto 2015-05-09 um 19 25 57](https://cloud.githubusercontent.com/assets/1425929/7551222/3caf5056-f681-11e4-8b1d-c08a3ccf94bd.png)

**Comment by donaier** [comment]
done
